"""A 4x4x10 Pareto/NBD grid with fixed within-year seasonality.

Four mean purchase rates x four churn rates, ten replicate panels per cell = 160
datasets of 1000 customers over 156 weeks (three years: two of calibration, one of
holdout). Seasonality is held fixed across the whole grid rather than varied, so the
only thing moving between cells is the (rate, churn) regime.

Copy this file to declare another grid; the module name is the grid's name and every
path derives from it.
"""

from __future__ import annotations

from panelclv.configs.panel_config import PanelConfig
from panelclv.studies import ModelSpec

from . import Arm, GridSpec

# ---------------------------------------------------------------------------
# The arm axis: how history is encoded, and how features become a vector
# ---------------------------------------------------------------------------
#
# The archived run of this grid trained one configuration — no AR features, no clusters,
# the registry's default `valendin` embedder — and found aggregate bias monotone in the
# panel's churn rate for both neural models (LSTM 40 -> 84 -> 162 -> 358%), against a
# Pareto/NBD that stays inside +/-16% (docs/insights-study.md §2). The reading there is
# that the neural models have no way to represent a customer who has stopped buying.
#
# These arms ask whether a *representation* of that customer's history fixes it, and the
# grid is the right place to ask because these panels are generated BY a Pareto/NBD:
# `AR_UNBOUNDED` below is literally the true model's own sufficient statistic (t_x, x, T),
# and the Pareto/NBD's own error is the known ceiling. On the real panels of
# run_ar_encoding_ablation.py the same question can only be asked against an unknown truth.
#
# Three axes, fully crossed:
#
#   AR encoding   no_ar / ar_unbounded / ar_bounded  — the same history as nothing, as
#                 unbounded counters, and as bounded flags that cannot leave the range
#                 the weights were fitted on
#   cluster       no_cluster / kmeans_8              — the same triple as a frozen
#                 category instead of a counter
#   embedder      valendin only                      — how any of it becomes a vector
#
# The embedder axis is DECLARED BUT NOT CROSSED. `projected` was measured to run (see
# scripts/preflight_grid_arms.py) and was cut on cost, not on doubt: it doubles the grid
# for the axis least likely to move the failure this grid is about, since ADR-0005's seam
# changes how features become a vector and the diagnosed problem is that the model has no
# way to represent a customer who has stopped. Adding "projected" back to EMBEDDER_AXIS
# below is the only edit needed to run it, and doubles the bill.
#
# `no_ar` x `no_cluster` x `valendin` is the archived configuration, so it doubles as
# this run's reproduction check: it must land near the numbers in insights-study.md §2
# or something has moved underneath the grid.

# The Pareto/NBD sufficient statistics. Two of the three are capped by the calibration
# window and keep counting through the holdout, which is the diagnosed failure
# (docs/insights-study.md §4.3) — this arm exists to reproduce it where the truth is known.
AR_UNBOUNDED = (
    "period_since_last_transaction",
    "cumulative_transactions",
    "period_since_first_transaction",
)

# The same silence, step-encoded. Every flag is 0 beyond its bin, so no holdout value can
# leave the fitted range. The deepest bin is 32 of the 104 calibration periods (~31%);
# at or above the window length a flag can never be 0 while fitting and the column
# degenerates into a duplicate of `has_transacted_before`. `active_in_last_1_periods` is
# omitted because the target channel already carries the previous count.
AR_BOUNDED = tuple(
    f"active_in_last_{k}_periods" for k in (2, 4, 8, 16, 32)
) + ("has_transacted_before",)

AR_AXIS = {"no_ar": (), "ar_unbounded": AR_UNBOUNDED, "ar_bounded": AR_BOUNDED}
CLUSTER_AXIS = {"no_cluster": (), "kmeans_8": ("kmeans_8",)}
# One entry, so the cross below is 3 x 2 x 1 = 6 arms. The registry default, and what
# the archived seasonal_4x4x10 run used — which is what makes the baseline arm a
# reproduction check rather than a new measurement.
EMBEDDER_AXIS = ("valendin",)

# Crossed rather than written out as twelve rows: a factorial design is what the three
# tables above say, and a hand-copied cross product is where a cell goes missing.
ARMS = tuple(
    Arm(
        name=f"{ar}-{cluster}-{embedder}",
        ar_features=ar_features,
        cluster_features=cluster_features,
        embedder=embedder,
    )
    for ar, ar_features in AR_AXIS.items()
    for cluster, cluster_features in CLUSTER_AXIS.items()
    for embedder in EMBEDDER_AXIS
)


# The window dates must land inside the calendar the generator produces:
# start_year=1999 and n_weeks=156 gives 1999-2001, so two calibration years and one
# holdout year. Change n_weeks or start_year above and these move with them.
PANEL = PanelConfig(
    id_col="Id",
    target_col="Transactions",
    frequency="weekly",
    training_start="1999-01-01",
    training_end="2000-12-31",
    validation_start="2000-01-01",      # last calibration year = the temporal val split
    holdout_start="2001-01-01",
    holdout_end="2001-12-31",
    time_cols=("year", "week"),
    clip_target_upper=6,                # also the softmax head size (7 classes: 0..6)
    require_calibration_activity=True,
    time_features={"add_year_idx": True, "add_week_sin_cos": True},
    # Pure Pareto/NBD panels carry no covariates: the target's own past is the input.
    known_future=(),
    static=(),
    observed_past=(),
    embedded_cols={"Transactions": "auto"},
)

# 100 Optuna trials per dataset per arm. This is the single largest cost in the grid:
# it is paid 1,920 times per model (160 panels x 12 arms), so read VastAI/Rules.md §8
# before changing it. The earlier 20 was chosen precisely because the budget is paid
# once per dataset; at 100 the same reasoning says the panel or arm count has to come
# down to compensate, and that trade is recorded in the run's launch plan rather than
# here, because it is a decision about one run and not about the grid's design.
LSTM = ModelSpec(
    name="LSTM",
    model_type="lstm",
    n_trials=100,
    search_space={
        "batch_size":       {64, 128, 256},
        "learning_rate":    (1e-4, 1e-2, "log"),
        "embedding_dim":    {64, 128, 256},
        "lstm_hidden_size": {32, 64, 128},
        "dense_units":      {32, 64, 128},
        "dropout":          {0.0, 0.2, 0.4},
    },
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# Same trial budget as the LSTM so the two are compared on equal search effort. The
# search space is the one scripts/run_studies.py declares for the single-panel suite.
TRANSFORMER = ModelSpec(
    name="Transformer",
    model_type="transformer",
    n_trials=100,
    search_space={
        "batch_size":         {64, 128, 256},
        "d_model":            {32, 64, 128},
        "nhead":              {2, 4, 8},
        "num_encoder_layers": (1, 3, "int"),
        "dropout":            {0.0, 0.1, 0.2, 0.3},
        "learning_rate":      (1e-4, 3e-3, "log"),
        "weight_decay":       (1e-6, 1e-2, "log"),
    },
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# The Valendin reference implementation. Its architecture is FROZEN (ADR-0004) — the
# published memory_units=128 / dense_units=128 and raw sqrt(n)+1 embeddings — so no
# search space is declared here at all: it inherits the registry entry's, which offers
# only the three training hyperparameters. Naming a width would quietly unfreeze the
# benchmark. Same trial budget as the others so search effort stays comparable.
VALENDIN = ModelSpec(
    name="ValendinLSTM",
    model_type="valendin_lstm",
    n_trials=100,
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# No Optuna: one deterministic MCMC fit on BTYDplus's default settings. On synthetic
# Pareto/NBD data this is the *correct* model by construction, so it is the ceiling the
# neural models are measured against.
PARETO = ModelSpec(name="ParetoNBD", model_type="pareto_nbd")

GRID = GridSpec(
    name="seasonal_4x4x10",

    # --- axes ---------------------------------------------------------------
    mean_transaction_rates=[0.01, 0.05, 0.10, 0.30],
    churn_rates=[0.20, 0.40, 0.60, 0.80],
    n_weeks_for_churn_rate=52,

    # --- panels -------------------------------------------------------------
    n_customers=1000,
    n_weeks=156,
    n_datasets=10,
    base_seed=42,
    start_year=1999,
    r=2.0,
    s=2.0,

    # --- seasonality: spring, two summer peaks, year-end --------------------
    seasonal_peaks=[12, 25, 30, 47],
    seasonal_amplitude=1.5,
    seasonal_width=3,

    # --- training -----------------------------------------------------------
    panel=PANEL,
    models=(LSTM, TRANSFORMER, VALENDIN, PARETO),
    arms=ARMS,
    n_simulations=200,

    # How many vast.ai workers each model's (arm x dataset) work is split across.
    # 0 = run on the orchestrator instead of renting (VastAI/Rules.md §5).
    #
    # Weighted by MEASURED cost, not by model count. One suite at 20 trials / 200
    # simulations on the orchestrator's CPU (i5-9600KF, 4 cores) took 131 s for the LSTM
    # and over 40 minutes for the Transformer — a ratio of at least 18x, driven by the
    # attention rollout, which re-reads the whole sequence at every one of 52 steps for
    # every simulated path. An even split would leave the LSTM workers idle for most of
    # the run while the Transformer ones are still going.
    #
    # PROVISIONAL. That ratio is CPU-only, and Transformer training parallelises on a GPU
    # far better than a sequential rollout does, so the real ratio on rented hardware is
    # smaller and unmeasured — VastAI/Rules.md §7's survey is LSTM-only. 8:2 hedges
    # against a ratio anywhere from 4x to 18x; re-derive it from a probe before trusting
    # it (`run_pnbd_grid.py --max-suites 1 --suite-suffix probe`).
    workers={"transformer": 8, "lstm": 2, "valendin_lstm": 0, "pareto_nbd": 0},
)
