"""`seasonal_4x4x10` with the Pareto/NBD sufficient statistics as AR features.

Identical to `seasonal_4x4x10` in every generation parameter — same axes, same seeds,
same seasonality, same panels — so the two grids differ in exactly one thing: this one
hands the neural models the three statistics the Pareto/NBD likelihood is built on.
Run both and the difference is attributable to the features.

The question it asks: on data generated BY a Pareto/NBD process, where that model is
the correct one by construction and therefore the ceiling, does a neural model close
the gap when it is given the same summary of a customer's history that Pareto/NBD
conditions on? Or is the remaining gap about the functional form rather than the
information?

The three features are the model's sufficient statistics, not a resemblance to them
(Schmittlein et al.; Fader & Hardie):

    period_since_last_transaction   recency, t_x
    cumulative_transactions         frequency, x — the count of ACTIVE PERIODS
    period_since_first_transaction  observation age, T

`cumulative_transactions` counts periods with at least one purchase, which is the
Pareto/NBD x. `cumulative_count` — the running sum of the counts themselves — is the
one to avoid here: it is ≥ x whenever a week holds more than one purchase, and it is
not what the likelihood conditions on.

All three are recomputed from the SAMPLED count at every rollout step, so nothing
leaks (`docs/feature_engineering.md`).

Copy this file to declare another grid; the module name is the grid's name and every
path derives from it.
"""

from __future__ import annotations

from panelclv.configs.panel_config import PanelConfig
from panelclv.studies import ModelSpec

from . import GridSpec

# The window dates must land inside the calendar the generator produces:
# start_year=1999 and n_weeks=156 gives 1999-2001, so two calibration years and one
# holdout year. Change n_weeks or start_year below and these move with them.
PANEL = PanelConfig(
    id_col="Id",
    target_col="Transactions",
    frequency="weekly",
    training_start="1999-01-01",
    training_end="2000-12-31",
    validation_start="2000-01-01",      # last calibration year = the temporal val split
    holdout_start="2001-01-01",
    holdout_end="2001-12-31",
    time_cols=("year", "week"),
    clip_target_upper=6,                # also the softmax head size (7 classes: 0..6)
    require_calibration_activity=True,
    time_features={"add_year_idx": True, "add_week_sin_cos": True},
    # THE ONE DIFFERENCE FROM `seasonal_4x4x10`. Recency / frequency / observation age:
    # the (t_x, x, T) triple the Pareto/NBD likelihood is a function of. Feature order
    # here is the order they enter seq_cols, after the target and the cyclical pair —
    # so F = 6: Transactions, week_sin, week_cos, then these three.
    ar_features=(
        "period_since_last_transaction",     # t_x — recency
        "cumulative_transactions",           # x  — active periods, NOT cumulative_count
        "period_since_first_transaction",    # T  — observation age
    ),
    # Pure Pareto/NBD panels carry no covariates: the target's own past is the input.
    known_future=(),
    static=(),
    observed_past=(),
    embedded_cols={"Transactions": "auto"},
)

LSTM = ModelSpec(
    name="LSTM",
    model_type="lstm",
    n_trials=100,
    search_space={
        "batch_size":       {64, 128, 256},
        "learning_rate":    (1e-4, 1e-2, "log"),
        "embedding_dim":    {64, 128, 256},
        "lstm_hidden_size": {32, 64, 128},
        "dense_units":      {32, 64, 128},
        "dropout":          {0.0, 0.2, 0.4},
    },
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# The search space is the one scripts/run_studies.py declares for the single-panel
# suite. NOTE its trial budget is not the LSTM's above — see the header comment on
# `workers` for what that costs and what it means for the comparison.
TRANSFORMER = ModelSpec(
    name="Transformer",
    model_type="transformer",
    n_trials=20,
    search_space={
        "batch_size":         {64, 128, 256},
        "d_model":            {32, 64, 128},
        "nhead":              {2, 4, 8},
        "num_encoder_layers": (1, 3, "int"),
        "dropout":            {0.0, 0.1, 0.2, 0.3},
        "learning_rate":      (1e-4, 3e-3, "log"),
        "weight_decay":       (1e-6, 1e-2, "log"),
    },
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# The Valendin reference implementation. Its architecture is FROZEN (ADR-0004) — the
# published memory_units=128 / dense_units=128 and raw sqrt(n)+1 embeddings — so no
# search space is declared here at all: it inherits the registry entry's, which offers
# only the three training hyperparameters. Naming a width would quietly unfreeze the
# benchmark.
VALENDIN = ModelSpec(
    name="ValendinLSTM",
    model_type="valendin_lstm",
    n_trials=20,
    training={
        "n_epochs": 100,
        "patience": 7,
        "loss_type": "cross_entropy",
        "verbose": False,
    },
)

# No Optuna: one deterministic MCMC fit on BTYDplus's default settings. On synthetic
# Pareto/NBD data this is the *correct* model by construction, so it is the ceiling the
# neural models are measured against — and the reason the AR features above are worth
# isolating: they are exactly what this model gets to see.
PARETO = ModelSpec(name="ParetoNBD", model_type="pareto_nbd")

GRID = GridSpec(
    name="seasonal_4x4x10_ar",

    # --- axes ---------------------------------------------------------------
    mean_transaction_rates=[0.01, 0.05, 0.10, 0.30],
    churn_rates=[0.20, 0.40, 0.60, 0.80],
    n_weeks_for_churn_rate=52,

    # --- panels -------------------------------------------------------------
    # Identical to `seasonal_4x4x10`, base_seed included, so the generated panels are
    # the same data. Verify with the checksum in VastAI/Rules.md §2: it must match the
    # one recorded there, or the two grids are not comparable.
    n_customers=1000,
    n_weeks=156,
    n_datasets=10,
    base_seed=42,
    start_year=1999,
    r=2.0,
    s=2.0,

    # --- seasonality: spring, two summer peaks, year-end --------------------
    seasonal_peaks=[12, 25, 30, 47],
    seasonal_amplitude=1.5,
    seasonal_width=3,

    # --- training -----------------------------------------------------------
    panel=PANEL,
    models=(LSTM, TRANSFORMER, VALENDIN, PARETO),
    n_simulations=200,

    # EDIT ME: how many vast.ai workers each model's 160 datasets are split across.
    # 0 = run on the orchestrator instead of renting (VastAI/Rules.md §5).
    #
    # WARNING: this split was sized for a 10-trial LSTM. At n_trials=100 the LSTM is
    # 100 x 160 = 16,000 Optuna trials, ten times the budget Rules.md §5 sets for a
    # grid (20 per dataset, because it is paid 160 times over) and five times the
    # Transformer's. Two workers will not carry it. Re-measure per-dataset wall-clock
    # on one box before choosing this number.
    workers={"transformer": 7, "lstm": 2, "valendin_lstm": 0, "pareto_nbd": 0},
)
